name: Workflow 1

on:
  repository_dispatch:
    inputs:
      parameter1:
        description: 'Parameter for Workflow 1'
        required: true
        default: 'MytestChekc1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "Yeah,we are running This is Workflow 1 with parameter ${{ github.event.inputs.parameter1 }}"
