name: Dispatch Workflow

on:
  repository_dispatch:
    types: [custom-event]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Use custom input
        run: echo "Heybrothis is yfdsfsour Input value: ${{ github.event.client_payload.my_input }}"
