name: Wkxyzflow 1

on:
  repository_dispatch:
    types: [event-type-1]

jobs:
  brogtmk:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run job 1
        run: echo "This is Workflow 1"
